# 1. ビルダーステージ
FROM node:18-alpine AS builder
WORKDIR /my-app
COPY ./my-app/package*.json ./
RUN npm install
COPY ./my-app .
RUN npm run build

# 2. 実行ステージ
FROM node:18-alpine AS runner
WORKDIR /my-app
ENV NODE_ENV=production

# standalone で生成されたファイルと public, static をコピー
COPY --from=builder /my-app/public ./public
COPY --from=builder /my-app/.next/standalone ./
COPY --from=builder /my-app/.next/static ./.next/static

EXPOSE 3000
CMD ["node", "server.js"]